gui:
  border: rounded
  theme:
    activeBorderColor:
      - "#5ef1ff"
    inactiveBorderColor:
      - "#7b8496"
    searchingActiveBorderColor:
      - "#ff5ef1"
    optionsTextColor:
      - "#3c4048"
    selectedLineBgColor:
      - "#3c4048"
    cherryPickedCommitBgColor:
      - "#3c4048"
    cherryPickedCommitFgColor:
      - "#ff5ea0"
    unstagedChangesColor:
      - "#ffbd5e"
    defaultFgColor:
      - "#ffffff"
quitOnTopLevelReturn: true
git:
  pagers:
    - pager: delta --dark --paging=never --diff-so-fancy --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  overrideGpg: true
os:
  editPreset: "nvim-remote"
